#nacos 版本
nacos_version: nacos-server-2.0.4

# nacos父目录
nacos_parent_dir: /usr/local

#运行端口
server_port: 8848

#链接数据库
datasource_username: "{{ common_mysql_username }}"
datasource_password: "{{ common_mysql_password }}"
datasource_url: jdbc:mysql://{{ common_mysql_host  | default(groups.mysql[0]) }}:3306/nacos?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

#初始化配置文件，如果不需要初始化请删除nacos_config下面配置
nacos_config_tenant: "{{ common_nacos_namespace }}"
nacos_config_group: G
nacos_config: # dataID之间 千万不要加换行，否则 有惊喜！
  - dataId: guc-extension.yml
    group: "guc-group"
    type: yaml
    content: "{{ guc_extension | from_yaml | to_nice_yaml(indent=2) }}"
    tenant: "{{ nacos_config_tenant }}"
  - dataId: guc-db.yml
    group: "guc-group"
    type: yaml
    content: "{{ guc_db_hs | from_yaml | to_nice_yaml(indent=2) }}"
    tenant: "{{ nacos_config_tenant }}"
  - dataId: spa-db.yml
    group: "spa-group"
    type: yaml
    content: "{{ spa_db_hs | from_yaml | to_nice_yaml(indent=2) }}"
    tenant: "{{ nacos_config_tenant }}"
  - dataId: spa-extension.yml
    group: "spa-group"
    type: yaml
    content: "{{ spa_extension | from_yaml | to_nice_yaml(indent=2) }}"
    tenant: "{{ nacos_config_tenant }}"
  - dataId: spa-oauth2.yml
    group: "spa-group"
    type: yaml
    content: "{{ spa_oauth2 | from_yaml | to_nice_yaml(indent=2) }}"
    tenant: "{{ nacos_config_tenant }}"
  - dataId: iiot-app-metadata-db.yml
    group: "iiot-app-metadata-group"
    type: yaml
    content: "{{ iiot_app_metadata_db | from_yaml | to_nice_yaml(indent=2) }}"
    tenant: "{{ nacos_config_tenant }}"

#  - dataId: gateway.openapi.json
#    group: "{{ nacos_config_group }}"
#    type: json
#    content: "{{ gateway_openapi | from_json | to_nice_json(indent=2) }}"
#    tenant: "{{ nacos_config_tenant }}"
