- name: "关闭并禁用防火墙"
  service: name=firewalld state=stopped enabled=no

- name: "禁用SELINUX"
  selinux: state=disabled

- name: "同步系统时区"
  shell: mv /etc/localtime /etc/localtime.bak; ln -s /usr/share/zoneinfo/Asia/Shanghai  /etc/localtime
