@startuml
'https://plantuml.com/sequence-diagram

actor User #red
participant "前端"
control     控制器
participant "业务层"
entity      实体
database    持久层

autonumber

title 插件管理
User -> 前端: 插件分类列表
User -> 前端: 插件应用详情
User -> 前端: 网关插件列表
前端 -> 控制器: 发起列表请求
控制器-> 业务层: 调用查询方法
业务层-> 持久层: 封装查询请求
持久层-> 实体: 封装实体查询结果
实体 ->业务层: 返回实体列表
业务层 ->控制器: 返回查询结果
控制器->前端: 返回请求响应
前端->User: 渲染展示

newpage 固件包管理
autonumber

User -> 前端: 添加网关/插件/驱动固件
前端 -> 控制器: 发起添加请求
控制器-> 业务层: 调用数据库存储
业务层-> 持久层: 封装保存请i去
持久层-> 实体: 返回添加结果
实体 ->业务层: 返回实体
业务层 ->控制器: 返回添加实体
控制器->前端: 返回请求响应
前端->User: 渲染展示
User -> 前端: 查询网关/插件/驱动固件
前端 -> 控制器: 发起列表请求
控制器-> 业务层: 调用查询方法
业务层-> 持久层: 封装查询请求
持久层-> 实体: 封装实体查询结果
实体 ->业务层: 返回实体列表
业务层 ->控制器: 返回查询结果
控制器->前端: 返回请求响应
前端->User: 渲染展示

newpage 升级任务管理

autonumber

participant "链路层"
actor Device #red

User -> 前端: 添加固件升级任务
前端 -> 控制器: 发起创建升级任务
控制器-> 业务层: 发起创建任务
业务层-> 持久层: 任务保存
业务层-> 链路层: 发送升级任务到设备
链路层 ->Device: 设备下载升级包进行升级
Device ->链路层: 返回升级任务结果
链路层->持久层: 更新任务信息
Device ->链路层: 上线事件
链路层-> 业务层: 设备固件信息
业务层 ->链路层: 检查固件任务，发布待升级任务
链路层 ->Device: 设备下载升级包进行升级
Device ->链路层: 返回升级任务结果
链路层->持久层: 更新任务信息
User -> 前端: 查询升级任务详情
前端 -> 控制器: 发起列表请求
控制器-> 业务层: 调用查询方法
业务层-> 持久层: 封装查询请求
持久层-> 实体: 封装实体查询结果
实体 ->业务层: 返回实体列表
业务层 ->控制器: 返回查询结果
控制器->前端: 返回请求响应
前端->User: 渲染展示

@enduml
