- name: "创建Minio用户"
  shell: id {{ minio_run_user }} || useradd {{ minio_run_user }} && echo '{{ minio_run_user }}:cc@123' | chpasswd

- name: "创建MinIO执行程序目录"
  file:
    path: "{{ minio_base_dir }}/bin"
    mode: "0755"
    state: directory

- name: "创建MinIO数据目录"
  file:
    path: "{{ minio_base_dir }}/data"
    mode: "0755"
    state: directory

- name: "拷贝MinIO执行程序"
  copy:
    src: "{{ playbook_dir }}/roles/minio/files/minio"
    dest: "{{ minio_base_dir }}/bin"
    force: yes
    mode: a+x

- name: "拷贝MC操作命令"
  copy:
    src: "{{ playbook_dir }}/roles/minio/files/mc"
    dest: "{{ minio_base_dir }}/bin"
    force: yes
    mode: a+x


- name: "上传脚本"
  template:
    dest: "{{ item.destfile }}"
    src: "{{ item.srcfile }}"
    mode: u+x
  with_items:
    - { srcfile: "minio.sh.j2", destfile: "/etc/profile.d/minio.sh" }
    - { srcfile: "server-minio.sh.j2" , destfile: "/etc/init.d/server-minio.sh" }

- name: "检查是否已经启动，如果启动先关闭已启动程序"
  shell: source /etc/profile; ps -ef | grep  {{ minio_base_dir }}/bin/minio  |  grep -v grep  | awk '{print $2}'  |  uniq | xargs -I {} kill -9 {}

- name: "启动"
  shell: source /etc/profile; grep server-minio.sh /etc/rc.d/rc.local || echo "/etc/init.d/server-minio.sh start" >> /etc/rc.d/rc.local && chmod +x /etc/rc.d/rc.local && chown {{ minio_run_user }}:{{ minio_run_user }} {{ minio_base_dir }} -R ; su - {{ minio_run_user }} -c "sh /etc/init.d/server-minio.sh start"

- name: "延时60s等待启动"
  shell: sleep 60s


- name: "复制默认上传文件脚本"
  template:
    src: "{{ playbook_dir }}/roles/minio/templates/data_init.sh.j2"
    dest: "{{ minio_base_dir }}/data_init.sh"
    mode: "0777"
  when: inventory_hostname == groups.minio[0]

- name: "创建临时存储上传文件目录"
  file:
    path: "{{ minio_base_dir }}/images"
    mode: "0766"
    state: directory
  when: inventory_hostname == groups.minio[0]

- name: "复制默认上传文件"
  copy:
    src: "{{ playbook_dir }}/roles/minio/files/images"
    dest: "{{ minio_base_dir }}/"
    force: yes
  when: inventory_hostname == groups.minio[0]

- name: "执行上传文件脚本"
  shell: source /etc/profile; sh {{ minio_base_dir }}/data_init.sh
  when: inventory_hostname == groups.minio[0]




