- name: "check install"
  shell: source /etc/profile; ps -ef | grep  redis |  grep -v grep  | awk '{print $2}'  |  uniq
  register: checkMsg
- name:
  block:
    - debug:
        msg: "已安装，自动跳过"
    - meta: end_play
  when: checkMsg.stdout != ""

- name: "安装依赖"
  yum:
    name: ['gcc', 'make', 'gcc-c++', 'pcre', 'pcre-devel', 'zlib', 'zlib-devel', 'openssl-devel', 'perl', 'unzip']
    state: installed

- name: "解压安装包"
  unarchive: src={{ playbook_dir }}/files/{{ redis_version }}.tar.gz dest={{ redis_parent_dir }}

- name: "安装Redis"
  shell: cd {{ redis_parent_dir }}/{{ redis_version }} && make

- name: "确保Redis的数据目录存在"
  file:
    path: "{{ redis_data_dir }}"
    state: directory

- name: "确保Redis的日志目录存在"
  file:
    path: "{{ redis_log_dir }}"
    state: directory

- name: "拷贝Redis配置文件"
  template:
    src: "{{ playbook_dir }}/roles/redis/redis_sentinel/templates/redis.conf.j2"
    dest: "{{ redis_parent_dir }}/{{ redis_version }}/redis.conf"

- name: "确保Sentinel目录存在"
  file:
    path: "{{ redis_sentinel_dir }}"
    state: directory

- name: "拷贝Sentinel配置文件"
  template:
    src: "{{ playbook_dir }}/roles/redis/redis_sentinel/templates/sentinel.conf.j2"
    dest: "{{ redis_parent_dir }}/{{ redis_version }}/sentinel.conf"

- name: "启动Redis"
  shell: "{{ redis_parent_dir }}/{{ redis_version }}/src/redis-server {{ redis_parent_dir }}/{{ redis_version }}/redis.conf"

- name: "启动Sentinel"
  shell: "{{ redis_parent_dir }}/{{ redis_version }}/src/redis-sentinel {{ redis_parent_dir }}/{{ redis_version }}/sentinel.conf"

- name: "拷贝Redis配置文件"
  template:
    src: "{{ playbook_dir }}/roles/redis/redis_sentinel/templates/redis_start.sh.j2"
    dest: "/etc/init.d/redis_start.sh"

- name: "添加开机启动到系统执行脚本"
  lineinfile: path=/etc/rc.d/rc.local line="/etc/init.d/redis_start.sh"

- name: "设置开机启动"
  shell: source /etc/profile; chmod +x /etc/rc.d/rc.local; chmod +x /etc/init.d/redis_start.sh
