package com.wujt.phoenixhbase.dao;


import com.wujt.phoenixhbase.entity.LStudent;
import com.wujt.phoenixhbase.entity.LStudentExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface LStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table L_STUDENT
     *
     * @mbg.generated
     */
    long countByExample(LStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table L_STUDENT
     *
     * @mbg.generated
     */
    int deleteByExample(LStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table L_STUDENT
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table L_STUDENT
     *
     * @mbg.generated
     */
    List<LStudent> selectByExample(LStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table L_STUDENT
     *
     * @mbg.generated
     */
    LStudent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table L_STUDENT
     *
     * @mbg.generated
     */
    int upsert(LStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table L_STUDENT
     *
     * @mbg.generated
     */
    int upsertSelective(LStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table L_STUDENT
     *
     * @mbg.generated
     */
    int batchUpsert(@Param("list") List<LStudent> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table L_STUDENT
     *
     * @mbg.generated
     */
    int batchUpsertSelective(@Param("list") List<LStudent> list, @Param("selective") LStudent.Column... selective);
}