spring:
  datasource:
    url: jdbc:mysql://mysql-mysqlha-write.mysql.svc.cluster.local:3306/wjt_quartz?useLegacyDatetimeCode=false&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
#    hikari:
#      maximum-pool-size: 10
#      connection-init-sql: SET NAMES utf8mb4
  quartz:
    #数据库方式
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: DefaultQuartzScheduler1
            instanceId: AUTO
#            skip-update-check: true
            jobFactory:
              class: com.wujt.quartz.config.MyJobFactory
            rmi:
              export: false
              proxy: false
              registryHost: localhost
              registryPort: 1099
            jmx:
              export: false
              proxy:
                class:
            wrapJobExecutionInUserTransaction: false
            dbFailureRetryInterval: 15000
            idleWaitTime: 30000
            makeSchedulerThreadDaemon: false
            threadsInheritInitializersClassLoadContext: false
            batchTriggerAcquisitionFireAheadTimeWindow: 0
            batchTriggerAcquisitionMaxCount: 1
            interruptJobsOnShutdown: false
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 1000
            useProperties: true
            misfireThreshold: 60000
#          使用starter自动进行dataSource 配置
#            dataSource: quartzDataSource
#          dataSource:
#            quartzDataSource:
#              driver: ${spring.datasource.driver-class-name}
#              URL: ${spring.datasource.url}
#              user: ${spring.datasource.username}
#              password: ${spring.datasource.password}
#              maxConnections: 5
#              validationQuery: select 0
#              provider: hikaricp
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true