- name: "安装依赖"
  yum:
    name: ['gcc-c++', 'pcre', 'pcre-devel', 'zlib', 'zlib-devel', 'openssl', 'openssl-devel', 'unzip']
    state: installed

- name: "解压安装包"
  unarchive: src={{ playbook_dir }}/files/{{ nginx_version }}.tar.gz dest={{ nginx_parent_dir }}

- name: "配置Nginx"
  shell: cd {{ nginx_parent_dir }}/{{ nginx_version }} && ./configure --prefix=/usr/local/nginx --with-http_stub_status_module --with-http_gzip_static_module --with-stream=dynamic

- name: "编译安装"
  shell: cd {{ nginx_parent_dir }}/{{ nginx_version }} && make && make install

- name: "拷贝配置文件nginx.conf"
  template:
    src: "{{ playbook_dir }}/roles/nginx/templates/nginx.conf.j2"
    dest: /usr/local/nginx/conf/nginx.conf

- name: "创建app配置目录"
  file:
    path: /usr/local/nginx/conf/app
    mode: "0755"
    state: directory

- name: "拷贝nacos置文件"
  copy:
    src: "{{ playbook_dir }}/roles/nginx/files/app/nacos.conf"
    dest: /usr/local/nginx/conf/app/nacos.conf

- name: "拷贝upstream置文件"
  template:
    src: "{{ playbook_dir }}/roles/nginx/templates/upstream.conf"
    dest: /usr/local/nginx/conf/app/upstream.conf

- name: "创建日志目录"
  file:
    path: /var/log/nginx
    mode: "0755"
    state: directory

- name: "启动nginx"
  shell: cd /usr/local/nginx/sbin && ./nginx
