@startuml
'https://plantuml.com/component-diagram


package "Cloud Gateway" {
  [Network]
  [Network Config]
  [NetworkProvider]
  }
  left to right direction
  package "ServerNetwork" {

        [Codec]
         note right: Frame,Message
        [Authenticator]
        [MessageProtocol]
        [SessionManager]
    }


@enduml
