package com.gow.mysql.dao;

import com.gow.mysql.model.Orderc;
import com.gow.mysql.model.OrdercExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdercMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderc
     *
     * @mbg.generated
     */
    long countByExample(OrdercExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderc
     *
     * @mbg.generated
     */
    int deleteByExample(OrdercExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderc
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderc
     *
     * @mbg.generated
     */
    int insert(Orderc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderc
     *
     * @mbg.generated
     */
    int insertSelective(Orderc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderc
     *
     * @mbg.generated
     */
    List<Orderc> selectByExample(OrdercExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderc
     *
     * @mbg.generated
     */
    Orderc selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderc
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Orderc record, @Param("example") OrdercExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderc
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Orderc record, @Param("example") OrdercExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderc
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Orderc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderc
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Orderc record);
}