- name: "解压安装包"
  unarchive:
    src: "{{ playbook_dir }}/{{ kafka_tar_name }}.tgz"
    dest: "{{ kafka_parent_dir }}"

- name: "创建Kafka日志目录"
  file:
    path: "{{ logs_dir }}"
    mode: "0755"
    state: directory

- name: "更新Kafka服务器配置文件"
  template:
    src: "{{ playbook_dir }}/roles/kafka/kafka_cluster/templates/server.properties.j2"
    dest: "{{ kafka_parent_dir }}/{{ kafka_tar_name }}/config/server.properties"

- name: "更新producer配置文件"
  template:
    src: "{{ playbook_dir }}/roles/kafka/kafka_cluster/templates/producer.properties.j2"
    dest: "{{ kafka_parent_dir }}/{{ kafka_tar_name }}/config/producer.properties"

- name: "添加执行文件权限"
  shell: chmod +x {{ kafka_parent_dir }}/{{ kafka_tar_name }}/bin/*

- name: "检查是否已经启动，如果启动先关闭已启动程序"
  shell: source /etc/profile; ps -ef | grep  {{ kafka_tar_name }}  |  grep -v grep  | awk '{print $2}'  |  uniq | xargs -I {} kill -9 {}

- name: "启动Kafka"
  shell: source /etc/profile; sh {{ kafka_parent_dir }}/{{ kafka_tar_name }}/bin/kafka-server-start.sh -daemon {{ kafka_parent_dir }}/{{ kafka_tar_name }}/config/server.properties
  tags: startKafka


- name: "添加开机启动到系统执行脚本"
  lineinfile: path=/etc/rc.d/rc.local line="su - root -c '{{ kafka_parent_dir }}/{{ kafka_tar_name }}/bin/kafka-server-start.sh -daemon {{ kafka_parent_dir }}/{{ kafka_tar_name }}/config/server.properties'"

- name: "设置开机启动"
  shell: source /etc/profile; chmod +x /etc/rc.d/rc.local;