version: '2'
services:
  srs:
    image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:4
    container_name: srs
    environment:
      - "TZ=Asia/Shanghai"
#      - "CANDIDATE=192.168.22.222"
    ports:
      - 1935:1935
      - 1985:1985
      - 8180:8080
      - 9100:9000/udp
      - 8000:8000/udp
      - 58200:58300
      - 58200:58300/udp
      - 5060:5060/udp
    volumes:
      - "./srs.conf:/usr/local/srs/conf/srs.conf"
