- name: "解压安装包"
  unarchive:
    src: "{{ playbook_dir }}/files/{{ zookeeper_tar_name }}.tar.gz"
    dest: "{{ zookeeper_parent_dir }}"

- name: "更新配置文件"
  template:
    src: "{{ playbook_dir }}/roles/zookeeper/zookeeper_standalone/templates/zoo.cfg.j2"
    dest: "{{ zookeeper_parent_dir }}/{{ zookeeper_tar_name }}/conf/zoo.cfg"

- name: "创建数据目录"
  file:
    path: "{{ zookeeper_parent_dir }}/{{ zookeeper_tar_name }}/data"
    mode: "0755"
    state: directory

- name: "创建日志目录"
  file:
    path: "{{ zookeeper_parent_dir }}/{{ zookeeper_tar_name }}/dataLogDir"
    mode: "0755"
    state: directory

- name: "创建myid"
  shell: echo {{ myid }} > {{ zookeeper_parent_dir }}/{{ zookeeper_tar_name }}/data/myid

- name: "检查是否已经启动，如果启动先关闭已启动程序"
  shell: source /etc/profile; ps -ef | grep  {{ zookeeper_tar_name }}  |  grep -v grep  | awk '{print $2}'  |  uniq | xargs -I {} kill -9 {}

- name: "启动Zookeeper"
  shell: source /etc/profile; sh {{ zookeeper_parent_dir }}/{{ zookeeper_tar_name }}/bin/zkServer.sh start
  tags: startZookeeper

- name: "添加开机启动到系统执行脚本"
  lineinfile: path=/etc/rc.d/rc.local line="su - root -c '{{ zookeeper_parent_dir }}/{{ zookeeper_tar_name }}/bin/zkServer.sh start'"

- name: "设置开机启动"
  shell: source /etc/profile; chmod +x /etc/rc.d/rc.local;