# 安装基础环境
- name: Common Configuration
  hosts: all
  remote_user: root
  roles:
    - common
    - jdk

# 安装ElastiCsearch
- name: Install ElastiCsearch
  hosts: elasticsearch_cluster
  remote_user: root
  roles:
    - elasticsearch/elasticsearch_cluster

# 安装cassandra
- name: Install Cassandra Cluster
  hosts: cassandra_cluster
  remote_user: root
  roles:
    - cassandra/cassandra_cluster

# 安装mysql
- name: Install MySQL Master Slave
  hosts: mysql
  remote_user: root
  roles:
    - mysql/masterslave

# 安装minio
- name: Install MinIO
  hosts: minio
  remote_user: root
  roles:
    - minio

# 安装redis
- name: Install Redis Sentinel
  hosts: redis_sentinel
  remote_user: root
  roles:
    - redis/redis_sentinel

# 安装nacos
- name: Install Nacos
  hosts: nacos_cluster
  remote_user: root
  roles:
    - nacos/nacos_cluster
