# 安装基础环境
- name: Common Configuration
  hosts: all
  remote_user: root
  roles:
    - common
#    - jdk
#    - docker
# 安装nginx
- name: Install Nginx
  hosts: nginx
  remote_user: root
  roles:
    - nginx
