- name: "解压安装包"
  unarchive: src={{ playbook_dir }}/files/{{ java_tar }} dest={{ jdk_dir }}
  when: inventory_hostname in groups.jdk

- name: "设置JAVA_HOME环境变量"
  lineinfile: path=/etc/profile regexp='^(.*)JAVA_HOME=(.*)$' line='export JAVA_HOME={{ jdk_dir }}/{{ java_version }}'
  when: inventory_hostname in groups.jdk

- name: "设置CLASSPATH"
  lineinfile: path=/etc/profile line='export CLASSPATH=.:$JAVA_HOME/jre/lib/rt.jar:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar'
  when: inventory_hostname in groups.jdk

- name: "设置PATH"
  lineinfile: path=/etc/profile line='export PATH=${JAVA_HOME}/bin:$PATH'
  when: inventory_hostname in groups.jdk

- name: "source /etc/profile"
  shell: source /etc/profile
  when: inventory_hostname in groups.jdk
