version: "2.2"
services:
  jobmanager:
    image: flink:1.14.4-scala_2.11
    container_name: jobmanager
    ports:
      - "8081:8081"
      - "8088:8088"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: flink:1.14.4-scala_2.11
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1  # 配置多部署task manager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
